### ISSUE TITLE
编译报错 版本号一模一样报错

### ISSUE THREAD

**Issue by Chen-guang91** [FeilongTest/go-ddddocr#1]
GOROOT=D:\go1.21.3.windows-amd64\go #gosetup
GOPATH=C:\Users\Administrator\go #gosetup
D:\go1.21.3.windows-amd64\go\bin\go.exe build -o C:\Users\Administrator\AppData\Local\Temp\GoLand\___1go_build_go_ddddocr.exe . #gosetup
github.com/yalue/onnxruntime_go: build constraints exclude all Go files in C:\Users\Administrator\go\pkg\mod\github.com\yalue\onnxruntime_go@v1.5.0

**Comment by Chen-guang91** [comment]
换成amd64就报错
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x5b88d7]

goroutine 1 [running]:
github.com/yalue/onnxruntime_go.(*AdvancedSession).Destroy(0x0)
        C:/Users/Administrator/go/pkg/mod/github.com/yalue/onnxruntime_go@v1.5.0/onnxruntime_go.go:930 +0x17
panic({0x639740?, 0x5fc310?})
        D:/go1.21.3.windows-amd64/go/src/runtime/panic.go:920 +0x270
github.com/yalue/onnxruntime_go.(*AdvancedSession).Run.func1(0xc000346010?)
        C:/Users/Administrator/go/pkg/mod/github.com/yalue/onnxruntime_go@v1.5.0/onnxruntime_go.go:949 +0x12
github.com/yalue/onnxruntime_go.(*AdvancedSession).Run(0xc000346010?)
        C:/Users/Administrator/go/pkg/mod/github.com/yalue/onnxruntime_go@v1.5.0/onnxruntime_go.go:951 +0x13
main.main()
        C:/Users/Administrator/Downloads/goddddocrmaster/main.go:625 +0x835

**Comment by jqqjj** [comment]
相同的问题

**Comment by AYZSQ** [comment]
The given version [16] is not supported, only version 1 to 10 is supported in this build.
2024/10/18 13:23:41 Platform-specific initialization failed: Error setting ORT API base: 2

弱弱的问一下大佬,我这个报错是因为什么呀
